FROM golang:1.22 AS go-builder

WORKDIR /workspace/exporter
COPY exporter .
ARG GO_LDFLAGS=""
RUN CGO_ENABLED=0 GOOS=linux GO111MODULE=on make build

FROM scratch

COPY --from=go-builder /workspace/exporter/bin/hash /
ENTRYPOINT [ "/hash" ]