apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: insights-operator-runtime
  labels:
    app.kubernetes.io/name: insights-operator-runtime
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: insights-operator-runtime
  template:
    metadata:
      labels:
        app.kubernetes.io/name: insights-operator-runtime
    spec:
      serviceAccountName: insights-operator-runtime-sa
      hostPID: true
      # You must have create a secret named insights-operator-runtime-pull-secret to be able to pull the image
      imagePullSecrets:
        - name: insights-operator-runtime-pull-secret 
      containers:
        - name: insights-operator-runtime
          # Replace the image field it is is coming from another image registry
          image: quay.io/jmesnil/insights-operator-runtime:latest
          imagePullPolicy: Always
          env:
            - name: CONTAINER_RUNTIME_ENDPOINT
              value: unix:///crio.sock
          securityContext:
            privileged: true
            capabilities:
              drop:
                - ALL
              add:
                - CAP_SYS_ADMIN
          volumeMounts:
            - mountPath: /crio.sock
              name: crio-socket
      volumes:
        - name: crio-socket
          hostPath:
            path: /run/crio/crio.sock
            type: Socket