name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Format
      run: |-
        cd ./insights-operator-runtime
        cargo fmt -- --check
    - name: Build
      run: |-
        cd ./insights-operator-runtime
        cargo build --release --verbose
    - name: Run tests
      run: |-
        cd ./insights-operator-runtime
        cargo test --release --verbose
