name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  REGISTRY: ghcr.io
  IMAGE_BASENAME: jmesnil/insights-runtime

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Format
      run: |-
        cd ./extractor
        cargo fmt -- --check
    - name: Build
      run: |-
        cd ./extractor
        cargo build --release --verbose
    - name: Run tests
      run: |-
        cd ./extractor
        cargo test --release --verbose

  image:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}     
    - name: Build and push the extractor image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Containerfile
        platforms: linux/amd64
        push: true
        target: extractor
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}-extractor:latest
    - name: Build and push the exporter image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: Containerfile
        platforms: linux/amd64
        push: true
        target: exporter
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_BASENAME }}-exporter:latest
